include $(BUILD_DIR)/tests/tcg/loongarch64-linux-user/config-target.mak

SUBDIR = $(SRC_PATH)/linux-user/loongarch
VPATH += $(SUBDIR)

all: $(SUBDIR)/vdso-64.so

$(SUBDIR)/vdso-64.so: vdso.S vdso.ld vdso-asmoffset.h
	$(CC) -o $@ -nostdlib -shared -fpic -Wl,-h,linux-vdso.so.1 \
	  -Wl,--build-id=sha1 -Wl,--hash-style=both \
	  -Wl,--no-warn-rwx-segments -Wl,-z,max-page-size=4096 \
	  -Wl,-T,$(SUBDIR)/vdso.ld $<
